name: UI tests
run-name: Library UI tests

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - master

jobs:
  runLibUnitTests:
    name: Run lib unit tests
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Set up JDK environment
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle version
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7

      - name: Run unit tests
        run: |
          gradle tasks :lib:testDebugUnitTest
